CREATE TABLE `apikey` (
	`id` text PRIMARY KEY,
	`name` text,
	`start` text,
	`config_id` text DEFAULT 'default' NOT NULL,
	`request_count` integer DEFAULT 0 NOT NULL,
	`prefix` text,
	`key` text NOT NULL,
	`user_id` text,
	`enabled` integer DEFAULT true NOT NULL,
	`expires_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`last_request` integer,
	`reference_id` text NOT NULL,
	`last_refill_at` integer,
	`rate_limit_enabled` integer,
	`rate_limit_time_window` integer,
	`rate_limit_max` integer,
	`remaining` integer,
	`refill_amount` integer,
	`refill_interval` integer,
	`metadata` text,
	`permissions` text
);
